### ISSUE TITLE
feature request: auto-format permalink to oid in block settings

### ISSUE THREAD

**Issue by ndunand** [UbiCastTeam/moodle-block_easycastms#2]
Hello,

This is probably also relevant in other Ubicast Moodle plugins, but here is the thing:

Our teachers have a habit to use the Moodle Ubicast block to display a channel's content in their Moodle course. They do so by

1. Copying their channel permalink, for instance `https://our.nudgis.domain/permalink/c126###/`
2. Creating a new Nudgis block in their Moodle course
3. Pasting the permalink itself, which is not working because the block expects just the oid, i.e. `c126###`

This should be easy to address, thus making the end users' life easier, simply by adding some `preg_replace()` in the form processing. Something like 

`preg_replace('/^.*([clv][0-9a-z]{19}).*$/', '$1', $permalink);`

**Comment by sdiemer** [comment]
Hello,

Thank you for the suggestion, we will implement it as soon as possible.

Regards

**Comment by sdiemer** [comment]
I have fixed the issue in this commit:
https://github.com/UbiCastTeam/moodle-block_ubicast/commit/4f5d37926d4227894f5783daf660bca308a99df2

**Comment by ndunand** [comment]
Thanks @sdiemer , looking forward to this in the next release 😊

**Comment by sdiemer** [comment]
The change is released on moodle.org.
The change has been made on the 3 plugins.
