### ISSUE TITLE
Undefined property PHP warnings in new version

### ISSUE THREAD

**Issue by ndunand** [UbiCastTeam/moodle-block_easycastms#4]
**Using `block_ubicast 2.0 (Build: 2024070301)` on `Moodle 4.4.1 (Build: 20240610)`**

Pages with existing blocks display this error:

```
Warning: Undefined property: stdClass::$types in /var/www/moodle/blocks/ubicast/block_ubicast.php on line 96

Warning: Undefined property: stdClass::$orderby in /var/www/moodle/blocks/ubicast/block_ubicast.php on line 100
```

https://github.com/UbiCastTeam/moodle-block_ubicast/blob/main/block_ubicast.php#L96 and https://github.com/UbiCastTeam/moodle-block_ubicast/blob/main/block_ubicast.php#L100 should probably use `isset()`.

**Comment by sdiemer** [comment]
Hello,

Thank you for the report, I fixed that in pull request #5.

Regards
